name: FSM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build
    - name: change
      run: cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
