name: FSM CI

on:
  push:
    branches:    
      - master         # Push events on master branch
      - 'feature/**'   # Push events on feature branch
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: exec
      run: bin/FSMTest 1
